// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/infobloxopen/infoblox-go-client/v2 (interfaces: IBConnector)
//
// Generated by this command:
//
//	mockgen -destination=ibclientmock/connector.go -package=ibclientmock -mock_names=IBConnector=MockConnector github.com/infobloxopen/infoblox-go-client/v2 IBConnector
//

// Package ibclientmock is a generated GoMock package.
package ibclientmock

import (
	reflect "reflect"

	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockConnector is a mock of IBConnector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
	isgomock struct{}
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// CreateObject mocks base method.
func (m *MockConnector) CreateObject(obj ibclient.IBObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObject", obj)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObject indicates an expected call of CreateObject.
func (mr *MockConnectorMockRecorder) CreateObject(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObject", reflect.TypeOf((*MockConnector)(nil).CreateObject), obj)
}

// DeleteObject mocks base method.
func (m *MockConnector) DeleteObject(ref string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ref)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockConnectorMockRecorder) DeleteObject(ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockConnector)(nil).DeleteObject), ref)
}

// GetObject mocks base method.
func (m *MockConnector) GetObject(obj ibclient.IBObject, ref string, queryParams *ibclient.QueryParams, res any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", obj, ref, queryParams, res)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetObject indicates an expected call of GetObject.
func (mr *MockConnectorMockRecorder) GetObject(obj, ref, queryParams, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockConnector)(nil).GetObject), obj, ref, queryParams, res)
}

// UpdateObject mocks base method.
func (m *MockConnector) UpdateObject(obj ibclient.IBObject, ref string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObject", obj, ref)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateObject indicates an expected call of UpdateObject.
func (mr *MockConnectorMockRecorder) UpdateObject(obj, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObject", reflect.TypeOf((*MockConnector)(nil).UpdateObject), obj, ref)
}
