// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -exclude_interfaces=Client -destination=ibclientmock/objectmanager.go -package=ibclientmock -mock_names=objectManager=MockObjectManager
//

// Package ibclientmock is a generated GoMock package.
package ibclientmock

import (
	reflect "reflect"

	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectManager is a mock of objectManager interface.
type MockObjectManager struct {
	ctrl     *gomock.Controller
	recorder *MockObjectManagerMockRecorder
	isgomock struct{}
}

// MockObjectManagerMockRecorder is the mock recorder for MockObjectManager.
type MockObjectManagerMockRecorder struct {
	mock *MockObjectManager
}

// NewMockObjectManager creates a new mock instance.
func NewMockObjectManager(ctrl *gomock.Controller) *MockObjectManager {
	mock := &MockObjectManager{ctrl: ctrl}
	mock.recorder = &MockObjectManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectManager) EXPECT() *MockObjectManagerMockRecorder {
	return m.recorder
}

// GetDNSView mocks base method.
func (m *MockObjectManager) GetDNSView(name string) (*ibclient.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSView", name)
	ret0, _ := ret[0].(*ibclient.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSView indicates an expected call of GetDNSView.
func (mr *MockObjectManagerMockRecorder) GetDNSView(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSView", reflect.TypeOf((*MockObjectManager)(nil).GetDNSView), name)
}

// GetNetwork mocks base method.
func (m *MockObjectManager) GetNetwork(netview, cidr string, isIPv6 bool, ea ibclient.EA) (*ibclient.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork", netview, cidr, isIPv6, ea)
	ret0, _ := ret[0].(*ibclient.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockObjectManagerMockRecorder) GetNetwork(netview, cidr, isIPv6, ea any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockObjectManager)(nil).GetNetwork), netview, cidr, isIPv6, ea)
}

// GetNetworkView mocks base method.
func (m *MockObjectManager) GetNetworkView(name string) (*ibclient.NetworkView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkView", name)
	ret0, _ := ret[0].(*ibclient.NetworkView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkView indicates an expected call of GetNetworkView.
func (mr *MockObjectManagerMockRecorder) GetNetworkView(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkView", reflect.TypeOf((*MockObjectManager)(nil).GetNetworkView), name)
}
